name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2/6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Should build?
        id: should_build
        shell: bash
        run: |
          source utils.sh
          toml_prep "$(cat config.toml)"

          is_youtube_latest() {
            t=$(toml_get_table YouTube)
            v=$(toml_get "$t" "version") || v=
            if [ "$v" = latest ]; then
              cur_yt=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
              [ -z "$cur_yt" ] && return 1 # empty, fail=>dont build
              aav=$(toml_get "$t" "allow-alpha-version") || aav=false
              last_ver=$(get_apkmirror_vers youtube "$aav" | get_largest_ver)
              [ -z "$last_ver" ] && return 1 # cant fetch, dont build
              echo "current yt version: '$cur_yt'"
              echo "latest yt version: '$last_ver'"
              [ "$cur_yt" != "$last_ver" ] # test success=>build, fail=>dont build
            else
              return 1 # not experimental, dont build
            fi
          }

          is_cli_latest() {
            declare -r last_cli_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/j-hc/revanced-cli/releases/latest - | json_get 'browser_download_url')
            declare -r last_cli=${last_cli_url##*/}
            cur_cli=$(sed -n 's/.*CLI: \(.*\)/\1/p' build.md | xargs)
          is_patches_latest() {
            PATCHES_SRC=$(toml_get "$(toml_get_table "")" patches-source) || PATCHES_SRC="revanced/revanced-patches"
            last_patches_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/${PATCHES_SRC}/releases/latest | json_get 'browser_download_url' | grep 'jar')
            last_patches=${last_patches_url##*/}
            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)

            echo "current integrations version: $cur_cli"
            echo "latest integrations version: $last_cli"
            [ "$cur_cli" != "$last_cli" ] # test success=>build, fail=>dont build
          }
          is_integrations_latest() {
            mkdir -p temp
            declare -r last_integrations_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/revanced/revanced-integrations/releases/latest - | json_get 'browser_download_url')
            declare -r last_integrations=${last_integrations_url##*/}
            cur_integrations=$(sed -n 's/.*Integrations: \(.*\)/\1/p' build.md | xargs)

            echo "current integrations version: $cur_integrations"
            echo "latest integrations version: $last_integrations"
            [ "$cur_integrations" != "$last_integrations" ] # test success=>build, fail=>dont build
          }
          is_patches_latest() {
            PATCHES_SRC=$(toml_get "$(toml_get_table "")" patches-source) || PATCHES_SRC="revanced/revanced-patches"
            last_patches_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/${PATCHES_SRC}/releases/latest | json_get 'browser_download_url' | grep 'jar')
            last_patches=${last_patches_url##*/}
            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)
            
            echo "current patches version: $cur_patches"
            echo "latest patches version: $last_patches"
            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
          }
          if ! git checkout update; then
            echo "first time building!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          elif is_youtube_latest || is_cli_latest || is_integrations_latest || is_patches_latest; then
            echo "build!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          else
            echo "dont build!"
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          fi
    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  build:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit
